# Generated by Django 2.2.2 on 2019-06-09 21:09

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TaskList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('created_at', models.DateTimeField(blank=True, default=django.utils.timezone.now)),
                ('due_on', models.DateTimeField(blank=True, default=django.utils.timezone.now)),
                ('status', models.CharField(max_length=250)),
                ('task_list', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='api.TaskList')),
            ],
        ),
    ]
